#ifndef SCK_CONFIG_H
#define SCK_CONFIG_H

#define SCK_SOCKET_MAX_CONNECTIONS      50
#define SCK_LOG_LEVEL                   (SCK_LOG_LEVEL_WARNING | SCK_LOG_LEVEL_ERROR | SCK_LOG_LEVEL_CRITICAL)

#endif /* SCK_CONFIG_H */